Re-write tests for sign up component
- This mainly focuses on testing and simulating sign up attempts with
  _invalid_ input data and its related events
- Changing onClick event attribute value to be `props.onClick || null`,
  instead of `props.onClick || ""` in ternary operator, resolves an
  error `TypeError: func.apply is not a function`

Resolves: #116